package net.sadmush.mushroomstuff.item;

import net.fabricmc.fabric.api.itemgroup.v1.FabricItemGroup;
import net.minecraft.item.ItemGroup;
import net.minecraft.item.ItemGroups;
import net.minecraft.item.ItemStack;
import net.minecraft.item.Items;
import net.minecraft.registry.Registries;
import net.minecraft.registry.Registry;
import net.minecraft.text.Text;
import net.minecraft.util.Identifier;
import net.sadmush.mushroomstuff.MushroomStuff;
import net.sadmush.mushroomstuff.MushroomStuffClient;
import net.sadmush.mushroomstuff.block.ModBlocks;

public class ModItemGroups {
    public static final ItemGroup MUSHROOM_STUFF = Registry.register(Registries.ITEM_GROUP, new Identifier(MushroomStuff.MOD_ID, "spore"), FabricItemGroup.builder().displayName(Text.translatable("itemgroup.spore")).icon(() -> new ItemStack(Items.RED_MUSHROOM)).entries((displayContext, entries) -> {
        entries.add(ModItems.SPORE);
        entries.add(ModItems.GLOWING_SPORE);
        entries.add(ModItems.BAKED_SPORE);
        entries.add(ModItems.BURNT_SPORE);
        entries.add(ModItems.SPOREBEAN);
        entries.add(ModItems.RED_SPOREBEAN);
        entries.add(ModItems.YELLOW_SPOREBEAN);
        entries.add(ModItems.GREEN_SPOREBEAN);
        entries.add(ModItems.BLUE_SPOREBEAN);
        entries.add(ModItems.PURPLE_SPOREBEAN);
        entries.add(ModItems.GRAY_SPOREBEAN);
        entries.add(ModItems.ECHO_CLUSTER);
        entries.add(ModItems.GOOP_VACUUM);
        entries.add(ModItems.GOOP_VACUUM_90);
        entries.add(ModItems.GOOP_VACUUM_80);
        entries.add(ModItems.GOOP_VACUUM_70);
        entries.add(ModItems.GOOP_VACUUM_60);
        entries.add(ModItems.GOOP_VACUUM_50);
        entries.add(ModItems.GOOP_VACUUM_40);
        entries.add(ModItems.GOOP_VACUUM_30);
        entries.add(ModItems.GOOP_VACUUM_20);
        entries.add(ModItems.GOOP_VACUUM_10);
        entries.add(ModItems.SPORE_HARVESTER);
        entries.add(ModItems.SPORE_HARVESTER_80);
        entries.add(ModItems.SPORE_HARVESTER_60);
        entries.add(ModItems.SPORE_HARVESTER_40);
        entries.add(ModItems.SPORE_HARVESTER_20);
        entries.add(ModItems.SPOREBEAN_BAG);
        entries.add(ModItems.SPOREBEAN_BAG_7);
        entries.add(ModItems.SPOREBEAN_BAG_6);
        entries.add(ModItems.SPOREBEAN_BAG_5);
        entries.add(ModItems.SPOREBEAN_BAG_4);
        entries.add(ModItems.SPOREBEAN_BAG_3);
        entries.add(ModItems.SPOREBEAN_BAG_2);
        entries.add(ModItems.SPOREBEAN_BAG_1);
        entries.add(ModItems.RED_SPOREBEAN_BAG);
        entries.add(ModItems.RED_SPOREBEAN_BAG_7);
        entries.add(ModItems.RED_SPOREBEAN_BAG_6);
        entries.add(ModItems.RED_SPOREBEAN_BAG_5);
        entries.add(ModItems.RED_SPOREBEAN_BAG_4);
        entries.add(ModItems.RED_SPOREBEAN_BAG_3);
        entries.add(ModItems.RED_SPOREBEAN_BAG_2);
        entries.add(ModItems.RED_SPOREBEAN_BAG_1);
        entries.add(ModItems.YELLOW_SPOREBEAN_BAG);
        entries.add(ModItems.YELLOW_SPOREBEAN_BAG_7);
        entries.add(ModItems.YELLOW_SPOREBEAN_BAG_6);
        entries.add(ModItems.YELLOW_SPOREBEAN_BAG_5);
        entries.add(ModItems.YELLOW_SPOREBEAN_BAG_4);
        entries.add(ModItems.YELLOW_SPOREBEAN_BAG_3);
        entries.add(ModItems.YELLOW_SPOREBEAN_BAG_2);
        entries.add(ModItems.YELLOW_SPOREBEAN_BAG_1);
        entries.add(ModItems.GREEN_SPOREBEAN_BAG);
        entries.add(ModItems.GREEN_SPOREBEAN_BAG_7);
        entries.add(ModItems.GREEN_SPOREBEAN_BAG_6);
        entries.add(ModItems.GREEN_SPOREBEAN_BAG_5);
        entries.add(ModItems.GREEN_SPOREBEAN_BAG_4);
        entries.add(ModItems.GREEN_SPOREBEAN_BAG_3);
        entries.add(ModItems.GREEN_SPOREBEAN_BAG_2);
        entries.add(ModItems.GREEN_SPOREBEAN_BAG_1);
        entries.add(ModItems.BLUE_SPOREBEAN_BAG);
        entries.add(ModItems.BLUE_SPOREBEAN_BAG_7);
        entries.add(ModItems.BLUE_SPOREBEAN_BAG_6);
        entries.add(ModItems.BLUE_SPOREBEAN_BAG_5);
        entries.add(ModItems.BLUE_SPOREBEAN_BAG_4);
        entries.add(ModItems.BLUE_SPOREBEAN_BAG_3);
        entries.add(ModItems.BLUE_SPOREBEAN_BAG_2);
        entries.add(ModItems.BLUE_SPOREBEAN_BAG_1);
        entries.add(ModItems.PURPLE_SPOREBEAN_BAG);
        entries.add(ModItems.PURPLE_SPOREBEAN_BAG_7);
        entries.add(ModItems.PURPLE_SPOREBEAN_BAG_6);
        entries.add(ModItems.PURPLE_SPOREBEAN_BAG_5);
        entries.add(ModItems.PURPLE_SPOREBEAN_BAG_4);
        entries.add(ModItems.PURPLE_SPOREBEAN_BAG_3);
        entries.add(ModItems.PURPLE_SPOREBEAN_BAG_2);
        entries.add(ModItems.PURPLE_SPOREBEAN_BAG_1);
        entries.add(ModItems.GRAY_SPOREBEAN_BAG);
        entries.add(ModItems.GRAY_SPOREBEAN_BAG_7);
        entries.add(ModItems.GRAY_SPOREBEAN_BAG_6);
        entries.add(ModItems.GRAY_SPOREBEAN_BAG_5);
        entries.add(ModItems.GRAY_SPOREBEAN_BAG_4);
        entries.add(ModItems.GRAY_SPOREBEAN_BAG_3);
        entries.add(ModItems.GRAY_SPOREBEAN_BAG_2);
        entries.add(ModItems.GRAY_SPOREBEAN_BAG_1);

        entries.add(ModBlocks.SPORE_BLOCK);
        entries.add(ModBlocks.GLOWING_SPORE_BLOCK);
        entries.add(ModBlocks.DRIED_SPORE_BLOCK);
        entries.add(ModBlocks.DRIED_GLOWING_SPORE_BLOCK);
        entries.add(ModBlocks.GOOP);
    }).build());
    public static void registerItemGroups() {
        MushroomStuff.LOGGER.info("Registering Item Groups " + MushroomStuff.MOD_ID);
    }
}
