package net.sadmush.effectbeans.item;

import net.fabricmc.fabric.api.itemgroup.v1.FabricItemGroup;
import net.minecraft.item.ItemGroup;
import net.minecraft.item.ItemStack;
import net.minecraft.item.Items;
import net.minecraft.registry.Registries;
import net.minecraft.registry.Registry;
import net.minecraft.text.Text;
import net.minecraft.util.Identifier;
import net.sadmush.effectbeans.Beans;
import net.sadmush.effectbeans.block.ModBlocks;

public class ModItemGroups {
    public static final ItemGroup EFFECT_BEANS = Registry.register(Registries.ITEM_GROUP, new Identifier(Beans.MOD_ID, "spore"), FabricItemGroup.builder().displayName(Text.translatable("itemgroup.spore")).icon(() -> new ItemStack(ModItems.SPOREBEAN)).entries((displayContext, entries) -> {
        entries.add(ModItems.SPOREBEAN);
        entries.add(ModItems.RED_SPOREBEAN);
        entries.add(ModItems.ORANGE_SPOREBEAN);
        entries.add(ModItems.YELLOW_SPOREBEAN);
        entries.add(ModItems.GREEN_SPOREBEAN);
        entries.add(ModItems.BLUE_SPOREBEAN);
        entries.add(ModItems.PINK_SPOREBEAN);
        entries.add(ModItems.PURPLE_SPOREBEAN);
        entries.add(ModItems.GRAY_SPOREBEAN);
        entries.add(ModItems.WHITE_SPOREBEAN);
        entries.add(ModItems.SPOREBEAN_BAG);
        entries.add(ModItems.SPOREBEAN_BAG_7);
        entries.add(ModItems.SPOREBEAN_BAG_6);
        entries.add(ModItems.SPOREBEAN_BAG_5);
        entries.add(ModItems.SPOREBEAN_BAG_4);
        entries.add(ModItems.SPOREBEAN_BAG_3);
        entries.add(ModItems.SPOREBEAN_BAG_2);
        entries.add(ModItems.SPOREBEAN_BAG_1);
        entries.add(ModItems.RED_SPOREBEAN_BAG);
        entries.add(ModItems.RED_SPOREBEAN_BAG_7);
        entries.add(ModItems.RED_SPOREBEAN_BAG_6);
        entries.add(ModItems.RED_SPOREBEAN_BAG_5);
        entries.add(ModItems.RED_SPOREBEAN_BAG_4);
        entries.add(ModItems.RED_SPOREBEAN_BAG_3);
        entries.add(ModItems.RED_SPOREBEAN_BAG_2);
        entries.add(ModItems.RED_SPOREBEAN_BAG_1);
        entries.add(ModItems.ORANGE_SPOREBEAN_BAG);
        entries.add(ModItems.ORANGE_SPOREBEAN_BAG_7);
        entries.add(ModItems.ORANGE_SPOREBEAN_BAG_6);
        entries.add(ModItems.ORANGE_SPOREBEAN_BAG_5);
        entries.add(ModItems.ORANGE_SPOREBEAN_BAG_4);
        entries.add(ModItems.ORANGE_SPOREBEAN_BAG_3);
        entries.add(ModItems.ORANGE_SPOREBEAN_BAG_2);
        entries.add(ModItems.ORANGE_SPOREBEAN_BAG_1);
        entries.add(ModItems.YELLOW_SPOREBEAN_BAG);
        entries.add(ModItems.YELLOW_SPOREBEAN_BAG_7);
        entries.add(ModItems.YELLOW_SPOREBEAN_BAG_6);
        entries.add(ModItems.YELLOW_SPOREBEAN_BAG_5);
        entries.add(ModItems.YELLOW_SPOREBEAN_BAG_4);
        entries.add(ModItems.YELLOW_SPOREBEAN_BAG_3);
        entries.add(ModItems.YELLOW_SPOREBEAN_BAG_2);
        entries.add(ModItems.YELLOW_SPOREBEAN_BAG_1);
        entries.add(ModItems.GREEN_SPOREBEAN_BAG);
        entries.add(ModItems.GREEN_SPOREBEAN_BAG_7);
        entries.add(ModItems.GREEN_SPOREBEAN_BAG_6);
        entries.add(ModItems.GREEN_SPOREBEAN_BAG_5);
        entries.add(ModItems.GREEN_SPOREBEAN_BAG_4);
        entries.add(ModItems.GREEN_SPOREBEAN_BAG_3);
        entries.add(ModItems.GREEN_SPOREBEAN_BAG_2);
        entries.add(ModItems.GREEN_SPOREBEAN_BAG_1);
        entries.add(ModItems.BLUE_SPOREBEAN_BAG);
        entries.add(ModItems.BLUE_SPOREBEAN_BAG_7);
        entries.add(ModItems.BLUE_SPOREBEAN_BAG_6);
        entries.add(ModItems.BLUE_SPOREBEAN_BAG_5);
        entries.add(ModItems.BLUE_SPOREBEAN_BAG_4);
        entries.add(ModItems.BLUE_SPOREBEAN_BAG_3);
        entries.add(ModItems.BLUE_SPOREBEAN_BAG_2);
        entries.add(ModItems.BLUE_SPOREBEAN_BAG_1);
        entries.add(ModItems.PINK_SPOREBEAN_BAG);
        entries.add(ModItems.PINK_SPOREBEAN_BAG_7);
        entries.add(ModItems.PINK_SPOREBEAN_BAG_6);
        entries.add(ModItems.PINK_SPOREBEAN_BAG_5);
        entries.add(ModItems.PINK_SPOREBEAN_BAG_4);
        entries.add(ModItems.PINK_SPOREBEAN_BAG_3);
        entries.add(ModItems.PINK_SPOREBEAN_BAG_2);
        entries.add(ModItems.PINK_SPOREBEAN_BAG_1);
        entries.add(ModItems.PURPLE_SPOREBEAN_BAG);
        entries.add(ModItems.PURPLE_SPOREBEAN_BAG_7);
        entries.add(ModItems.PURPLE_SPOREBEAN_BAG_6);
        entries.add(ModItems.PURPLE_SPOREBEAN_BAG_5);
        entries.add(ModItems.PURPLE_SPOREBEAN_BAG_4);
        entries.add(ModItems.PURPLE_SPOREBEAN_BAG_3);
        entries.add(ModItems.PURPLE_SPOREBEAN_BAG_2);
        entries.add(ModItems.PURPLE_SPOREBEAN_BAG_1);
        entries.add(ModItems.GRAY_SPOREBEAN_BAG);
        entries.add(ModItems.GRAY_SPOREBEAN_BAG_7);
        entries.add(ModItems.GRAY_SPOREBEAN_BAG_6);
        entries.add(ModItems.GRAY_SPOREBEAN_BAG_5);
        entries.add(ModItems.GRAY_SPOREBEAN_BAG_4);
        entries.add(ModItems.GRAY_SPOREBEAN_BAG_3);
        entries.add(ModItems.GRAY_SPOREBEAN_BAG_2);
        entries.add(ModItems.GRAY_SPOREBEAN_BAG_1);
        entries.add(ModItems.WHITE_SPOREBEAN_BAG);
        entries.add(ModItems.WHITE_SPOREBEAN_BAG_7);
        entries.add(ModItems.WHITE_SPOREBEAN_BAG_6);
        entries.add(ModItems.WHITE_SPOREBEAN_BAG_5);
        entries.add(ModItems.WHITE_SPOREBEAN_BAG_4);
        entries.add(ModItems.WHITE_SPOREBEAN_BAG_3);
        entries.add(ModItems.WHITE_SPOREBEAN_BAG_2);
        entries.add(ModItems.WHITE_SPOREBEAN_BAG_1);
    }).build());
    public static void registerItemGroups() {
        Beans.LOGGER.info("Registering Item Groups " + Beans.MOD_ID);
    }
}
