package net.sadmush.mushroomstuff.datagen;

import net.fabricmc.fabric.api.datagen.v1.FabricDataOutput;
import net.fabricmc.fabric.api.datagen.v1.provider.FabricRecipeProvider;
import net.minecraft.block.Blocks;
import net.minecraft.data.server.recipe.RecipeJsonProvider;
import net.minecraft.data.server.recipe.ShapedRecipeJsonBuilder;
import net.minecraft.data.server.recipe.ShapelessRecipeJsonBuilder;
import net.minecraft.item.ItemConvertible;
import net.minecraft.item.Items;
import net.minecraft.recipe.book.RecipeCategory;
import net.minecraft.util.Identifier;
import net.sadmush.mushroomstuff.block.ModBlocks;
import net.sadmush.mushroomstuff.item.ModItems;
import net.sadmush.mushroomstuff.util.ModTags;

import java.util.List;
import java.util.function.Consumer;

public class ModRecipeProvider extends FabricRecipeProvider {
    private static final List<ItemConvertible> SPORE_SMELTABLES = List.of(ModItems.GLOWING_SPORE);
    private static final List<ItemConvertible> SPORE_BLOCK_SMELTABLES = List.of(ModBlocks.GLOWING_SPORE_BLOCK, ModBlocks.DRIED_SPORE_BLOCK);
    private static final List<ItemConvertible> GLOWING_SPORE_BLOCK_SMELTABLES = List.of(ModBlocks.DRIED_GLOWING_SPORE_BLOCK);
    private static final List<ItemConvertible> BAKED_SPORE_SMELTABLES = List.of(ModItems.SPORE);
    private static final List<ItemConvertible> BURNT_SPORE_SMELTABLES = List.of(ModItems.BAKED_SPORE);

    public ModRecipeProvider(FabricDataOutput output) {
        super(output);
    }

    @Override
    public void generate(Consumer<RecipeJsonProvider> consumer) {
        offerSmelting(consumer, SPORE_SMELTABLES, RecipeCategory.MISC, ModItems.SPORE, 0.15f, 100, "spore");
        offerSmelting(consumer, SPORE_BLOCK_SMELTABLES, RecipeCategory.MISC, ModBlocks.SPORE_BLOCK, 0.3f, 200, "spore");
        offerSmelting(consumer, GLOWING_SPORE_BLOCK_SMELTABLES, RecipeCategory.MISC, ModBlocks.GLOWING_SPORE_BLOCK, 0.3f, 200, "spore");
        offerSmelting(consumer, BAKED_SPORE_SMELTABLES, RecipeCategory.MISC, ModItems.BAKED_SPORE, 0.1f, 20, "spore");
        offerSmelting(consumer, BURNT_SPORE_SMELTABLES, RecipeCategory.MISC, ModItems.BURNT_SPORE, 0.1f, 100, "spore");

        ShapelessRecipeJsonBuilder.create(RecipeCategory.BUILDING_BLOCKS, ModBlocks.LARGE_GOO_BRICKS).input(ModBlocks.GOO, 1).input(Blocks.STONE_BRICKS, 1).criterion(hasItem(ModItems.SPORE), conditionsFromItem(ModItems.SPORE)).offerTo(consumer, new Identifier(getRecipeName(ModBlocks.LARGE_GOO_BRICKS)));
        ShapelessRecipeJsonBuilder.create(RecipeCategory.BUILDING_BLOCKS, ModBlocks.GOO_BRICKS).input(ModBlocks.GOO, 1).input(Blocks.BRICKS, 1).criterion(hasItem(ModItems.SPORE), conditionsFromItem(ModItems.SPORE)).offerTo(consumer, new Identifier(getRecipeName(ModBlocks.GOO_BRICKS)));
        ShapelessRecipeJsonBuilder.create(RecipeCategory.BUILDING_BLOCKS, ModBlocks.GOO).input(ModItems.SPORE, 4).criterion(hasItem(ModItems.SPORE), conditionsFromItem(ModItems.SPORE)).offerTo(consumer, new Identifier(getRecipeName(ModBlocks.GOO)));
        ShapedRecipeJsonBuilder.create(RecipeCategory.BUILDING_BLOCKS, ModBlocks.SPORE_BLOCK).input('#', ModItems.SPORE).pattern("###").pattern("###").pattern("###").group("spore").criterion(hasItem(ModItems.SPORE), conditionsFromItem(ModItems.SPORE)).offerTo(consumer, new Identifier(getRecipeName(ModBlocks.SPORE_BLOCK)));
        ShapedRecipeJsonBuilder.create(RecipeCategory.BUILDING_BLOCKS, ModBlocks.GLOWING_SPORE_BLOCK).input('#', ModItems.GLOWING_SPORE).pattern("###").pattern("###").pattern("###").group("spore").criterion(hasItem(ModItems.SPORE), conditionsFromItem(ModItems.SPORE)).offerTo(consumer, new Identifier(getRecipeName(ModBlocks.GLOWING_SPORE_BLOCK)));
        ShapedRecipeJsonBuilder.create(RecipeCategory.FOOD, ModItems.SPOREBEAN).input('#', ModItems.SPORE).input('+', Items.SUGAR).group("spore").pattern(" # ").pattern("#+#").pattern(" # ").criterion(hasItem(ModItems.SPORE), conditionsFromItem(ModItems.SPORE)).offerTo(consumer, new Identifier(getRecipeName(ModItems.SPOREBEAN)));
        ShapelessRecipeJsonBuilder.create(RecipeCategory.FOOD, ModItems.RED_SPOREBEAN).input(ModTags.Items.SPOREBEANS).input(Items.RED_DYE, 1).criterion(hasItem(ModItems.SPOREBEAN), conditionsFromItem(ModItems.SPOREBEAN)).group("spore").offerTo(consumer, new Identifier(getRecipeName(ModItems.RED_SPOREBEAN)));
        ShapelessRecipeJsonBuilder.create(RecipeCategory.FOOD, ModItems.YELLOW_SPOREBEAN).input(ModTags.Items.SPOREBEANS).input(Items.YELLOW_DYE, 1).criterion(hasItem(ModItems.SPOREBEAN), conditionsFromItem(ModItems.SPOREBEAN)).group("spore").offerTo(consumer, new Identifier(getRecipeName(ModItems.YELLOW_SPOREBEAN)));
        ShapelessRecipeJsonBuilder.create(RecipeCategory.FOOD, ModItems.GREEN_SPOREBEAN).input(ModTags.Items.SPOREBEANS).input(Items.GREEN_DYE, 1).criterion(hasItem(ModItems.SPOREBEAN), conditionsFromItem(ModItems.SPOREBEAN)).group("spore").offerTo(consumer, new Identifier(getRecipeName(ModItems.GREEN_SPOREBEAN)));
        ShapelessRecipeJsonBuilder.create(RecipeCategory.FOOD, ModItems.BLUE_SPOREBEAN).input(ModTags.Items.SPOREBEANS).input(Items.BLUE_DYE, 1).criterion(hasItem(ModItems.SPOREBEAN), conditionsFromItem(ModItems.SPOREBEAN)).group("spore").offerTo(consumer, new Identifier(getRecipeName(ModItems.BLUE_SPOREBEAN)));
        ShapelessRecipeJsonBuilder.create(RecipeCategory.FOOD, ModItems.PURPLE_SPOREBEAN).input(ModTags.Items.SPOREBEANS).input(Items.PURPLE_DYE, 1).criterion(hasItem(ModItems.SPOREBEAN), conditionsFromItem(ModItems.SPOREBEAN)).group("spore").offerTo(consumer, new Identifier(getRecipeName(ModItems.PURPLE_SPOREBEAN)));
        ShapelessRecipeJsonBuilder.create(RecipeCategory.FOOD, ModItems.GRAY_SPOREBEAN).input(ModTags.Items.SPOREBEANS).input(Items.GRAY_DYE, 1).criterion(hasItem(ModItems.SPOREBEAN), conditionsFromItem(ModItems.SPOREBEAN)).group("spore").offerTo(consumer, new Identifier(getRecipeName(ModItems.GRAY_SPOREBEAN)));
        ShapelessRecipeJsonBuilder.create(RecipeCategory.MISC, ModItems.GLOWING_SPORE, 8).input(ModItems.SPORE, 8).input(Items.GLOW_INK_SAC, 1).group("spore").criterion(hasItem(ModItems.SPORE), conditionsFromItem(ModItems.SPORE)).criterion(hasItem(Items.GLOW_INK_SAC), conditionsFromItem(Items.GLOW_INK_SAC)).offerTo(consumer, new Identifier(getRecipeName(ModItems.GLOWING_SPORE)));
        ShapelessRecipeJsonBuilder.create(RecipeCategory.MISC, Items.BLACK_DYE).input(ModItems.BURNT_SPORE, 1).criterion(hasItem(ModItems.BURNT_SPORE), conditionsFromItem(ModItems.BURNT_SPORE)).offerTo(consumer, new Identifier(getRecipeName(Items.BLACK_DYE)));
        ShapedRecipeJsonBuilder.create(RecipeCategory.TOOLS, ModItems.SPORE_HARVESTER).input('-', Items.IRON_INGOT).input('$', Items.REDSTONE_BLOCK).input('/', Items.GLASS).pattern("-  ").pattern(" $ ").pattern("  /").group("spore").criterion(hasItem(Items.IRON_INGOT), conditionsFromItem(Items.IRON_INGOT)).criterion(hasItem(Items.REDSTONE), conditionsFromItem(Items.REDSTONE)).criterion(hasItem(Items.GLASS), conditionsFromItem(Items.GLASS)).offerTo(consumer, new Identifier(getRecipeName(ModItems.SPORE_HARVESTER)));
        ShapedRecipeJsonBuilder.create(RecipeCategory.MISC, ModItems.ECHO_CLUSTER).input('#', Items.ECHO_SHARD).pattern(" # ").pattern("# #").pattern(" # ").group("spore").criterion(hasItem(ModItems.SPORE), conditionsFromItem(ModItems.SPORE)).criterion(hasItem(Items.ECHO_SHARD), conditionsFromItem(Items.ECHO_SHARD)).offerTo(consumer, new Identifier(getRecipeName(ModItems.ECHO_CLUSTER)));
        ShapelessRecipeJsonBuilder.create(RecipeCategory.DECORATIONS, ModBlocks.DRIED_SPORE_BLOCK).input(ModBlocks.SPORE_BLOCK, 1).input(Items.CLAY_BALL, 1).group("spore").criterion(hasItem(ModBlocks.SPORE_BLOCK), conditionsFromItem(ModBlocks.SPORE_BLOCK)).criterion(hasItem(Items.CLAY_BALL), conditionsFromItem(Items.CLAY_BALL)).offerTo(consumer, new Identifier(getRecipeName(ModBlocks.DRIED_SPORE_BLOCK)));
        ShapelessRecipeJsonBuilder.create(RecipeCategory.DECORATIONS, ModBlocks.DRIED_GLOWING_SPORE_BLOCK).input(ModBlocks.GLOWING_SPORE_BLOCK, 1).input(Items.CLAY_BALL, 1).group("spore").criterion(hasItem(ModBlocks.GLOWING_SPORE_BLOCK), conditionsFromItem(ModBlocks.GLOWING_SPORE_BLOCK)).criterion(hasItem(Items.CLAY_BALL), conditionsFromItem(Items.CLAY_BALL)).offerTo(consumer, new Identifier(getRecipeName(ModBlocks.DRIED_GLOWING_SPORE_BLOCK)));
        ShapelessRecipeJsonBuilder.create(RecipeCategory.MISC, ModItems.SPOREBEAN_BAG).input(ModItems.SPOREBEAN, 8).input(Items.PAPER, 1).criterion(hasItem(ModItems.SPOREBEAN), conditionsFromItem(ModItems.SPOREBEAN)).offerTo(consumer, new Identifier(getRecipeName(ModItems.SPOREBEAN_BAG)));
        ShapelessRecipeJsonBuilder.create(RecipeCategory.MISC, ModItems.SPOREBEAN_BAG_7).input(ModItems.SPOREBEAN, 7).input(Items.PAPER, 1).criterion(hasItem(ModItems.SPOREBEAN), conditionsFromItem(ModItems.SPOREBEAN)).offerTo(consumer, new Identifier(getRecipeName(ModItems.SPOREBEAN_BAG_7)));
        ShapelessRecipeJsonBuilder.create(RecipeCategory.MISC, ModItems.SPOREBEAN_BAG_6).input(ModItems.SPOREBEAN, 6).input(Items.PAPER, 1).criterion(hasItem(ModItems.SPOREBEAN), conditionsFromItem(ModItems.SPOREBEAN)).offerTo(consumer, new Identifier(getRecipeName(ModItems.SPOREBEAN_BAG_6)));
        ShapelessRecipeJsonBuilder.create(RecipeCategory.MISC, ModItems.SPOREBEAN_BAG_5).input(ModItems.SPOREBEAN, 5).input(Items.PAPER, 1).criterion(hasItem(ModItems.SPOREBEAN), conditionsFromItem(ModItems.SPOREBEAN)).offerTo(consumer, new Identifier(getRecipeName(ModItems.SPOREBEAN_BAG_5)));
        ShapelessRecipeJsonBuilder.create(RecipeCategory.MISC, ModItems.SPOREBEAN_BAG_4).input(ModItems.SPOREBEAN, 4).input(Items.PAPER, 1).criterion(hasItem(ModItems.SPOREBEAN), conditionsFromItem(ModItems.SPOREBEAN)).offerTo(consumer, new Identifier(getRecipeName(ModItems.SPOREBEAN_BAG_4)));
        ShapelessRecipeJsonBuilder.create(RecipeCategory.MISC, ModItems.SPOREBEAN_BAG_3).input(ModItems.SPOREBEAN, 3).input(Items.PAPER, 1).criterion(hasItem(ModItems.SPOREBEAN), conditionsFromItem(ModItems.SPOREBEAN)).offerTo(consumer, new Identifier(getRecipeName(ModItems.SPOREBEAN_BAG_3)));
        ShapelessRecipeJsonBuilder.create(RecipeCategory.MISC, ModItems.SPOREBEAN_BAG_2).input(ModItems.SPOREBEAN, 2).input(Items.PAPER, 1).criterion(hasItem(ModItems.SPOREBEAN), conditionsFromItem(ModItems.SPOREBEAN)).offerTo(consumer, new Identifier(getRecipeName(ModItems.SPOREBEAN_BAG_2)));
        ShapelessRecipeJsonBuilder.create(RecipeCategory.MISC, ModItems.RED_SPOREBEAN_BAG).input(ModItems.RED_SPOREBEAN, 8).input(Items.PAPER, 1).criterion(hasItem(ModItems.RED_SPOREBEAN), conditionsFromItem(ModItems.RED_SPOREBEAN)).offerTo(consumer, new Identifier(getRecipeName(ModItems.RED_SPOREBEAN_BAG)));
        ShapelessRecipeJsonBuilder.create(RecipeCategory.MISC, ModItems.RED_SPOREBEAN_BAG_7).input(ModItems.RED_SPOREBEAN, 7).input(Items.PAPER, 1).criterion(hasItem(ModItems.RED_SPOREBEAN), conditionsFromItem(ModItems.RED_SPOREBEAN)).offerTo(consumer, new Identifier(getRecipeName(ModItems.RED_SPOREBEAN_BAG_7)));
        ShapelessRecipeJsonBuilder.create(RecipeCategory.MISC, ModItems.RED_SPOREBEAN_BAG_6).input(ModItems.RED_SPOREBEAN, 6).input(Items.PAPER, 1).criterion(hasItem(ModItems.RED_SPOREBEAN), conditionsFromItem(ModItems.RED_SPOREBEAN)).offerTo(consumer, new Identifier(getRecipeName(ModItems.RED_SPOREBEAN_BAG_6)));
        ShapelessRecipeJsonBuilder.create(RecipeCategory.MISC, ModItems.RED_SPOREBEAN_BAG_5).input(ModItems.RED_SPOREBEAN, 5).input(Items.PAPER, 1).criterion(hasItem(ModItems.RED_SPOREBEAN), conditionsFromItem(ModItems.RED_SPOREBEAN)).offerTo(consumer, new Identifier(getRecipeName(ModItems.RED_SPOREBEAN_BAG_5)));
        ShapelessRecipeJsonBuilder.create(RecipeCategory.MISC, ModItems.RED_SPOREBEAN_BAG_4).input(ModItems.RED_SPOREBEAN, 4).input(Items.PAPER, 1).criterion(hasItem(ModItems.RED_SPOREBEAN), conditionsFromItem(ModItems.RED_SPOREBEAN)).offerTo(consumer, new Identifier(getRecipeName(ModItems.RED_SPOREBEAN_BAG_4)));
        ShapelessRecipeJsonBuilder.create(RecipeCategory.MISC, ModItems.RED_SPOREBEAN_BAG_3).input(ModItems.RED_SPOREBEAN, 3).input(Items.PAPER, 1).criterion(hasItem(ModItems.RED_SPOREBEAN), conditionsFromItem(ModItems.RED_SPOREBEAN)).offerTo(consumer, new Identifier(getRecipeName(ModItems.RED_SPOREBEAN_BAG_3)));
        ShapelessRecipeJsonBuilder.create(RecipeCategory.MISC, ModItems.RED_SPOREBEAN_BAG_2).input(ModItems.RED_SPOREBEAN, 2).input(Items.PAPER, 1).criterion(hasItem(ModItems.RED_SPOREBEAN), conditionsFromItem(ModItems.RED_SPOREBEAN)).offerTo(consumer, new Identifier(getRecipeName(ModItems.RED_SPOREBEAN_BAG_2)));
        ShapelessRecipeJsonBuilder.create(RecipeCategory.MISC, ModItems.YELLOW_SPOREBEAN_BAG).input(ModItems.YELLOW_SPOREBEAN, 8).input(Items.PAPER, 1).criterion(hasItem(ModItems.YELLOW_SPOREBEAN), conditionsFromItem(ModItems.YELLOW_SPOREBEAN)).offerTo(consumer, new Identifier(getRecipeName(ModItems.YELLOW_SPOREBEAN_BAG)));
        ShapelessRecipeJsonBuilder.create(RecipeCategory.MISC, ModItems.YELLOW_SPOREBEAN_BAG_7).input(ModItems.YELLOW_SPOREBEAN, 7).input(Items.PAPER, 1).criterion(hasItem(ModItems.YELLOW_SPOREBEAN), conditionsFromItem(ModItems.YELLOW_SPOREBEAN)).offerTo(consumer, new Identifier(getRecipeName(ModItems.YELLOW_SPOREBEAN_BAG_7)));
        ShapelessRecipeJsonBuilder.create(RecipeCategory.MISC, ModItems.YELLOW_SPOREBEAN_BAG_6).input(ModItems.YELLOW_SPOREBEAN, 6).input(Items.PAPER, 1).criterion(hasItem(ModItems.YELLOW_SPOREBEAN), conditionsFromItem(ModItems.YELLOW_SPOREBEAN)).offerTo(consumer, new Identifier(getRecipeName(ModItems.YELLOW_SPOREBEAN_BAG_6)));
        ShapelessRecipeJsonBuilder.create(RecipeCategory.MISC, ModItems.YELLOW_SPOREBEAN_BAG_5).input(ModItems.YELLOW_SPOREBEAN, 5).input(Items.PAPER, 1).criterion(hasItem(ModItems.YELLOW_SPOREBEAN), conditionsFromItem(ModItems.YELLOW_SPOREBEAN)).offerTo(consumer, new Identifier(getRecipeName(ModItems.YELLOW_SPOREBEAN_BAG_5)));
        ShapelessRecipeJsonBuilder.create(RecipeCategory.MISC, ModItems.YELLOW_SPOREBEAN_BAG_4).input(ModItems.YELLOW_SPOREBEAN, 4).input(Items.PAPER, 1).criterion(hasItem(ModItems.YELLOW_SPOREBEAN), conditionsFromItem(ModItems.YELLOW_SPOREBEAN)).offerTo(consumer, new Identifier(getRecipeName(ModItems.YELLOW_SPOREBEAN_BAG_4)));
        ShapelessRecipeJsonBuilder.create(RecipeCategory.MISC, ModItems.YELLOW_SPOREBEAN_BAG_3).input(ModItems.YELLOW_SPOREBEAN, 3).input(Items.PAPER, 1).criterion(hasItem(ModItems.YELLOW_SPOREBEAN), conditionsFromItem(ModItems.YELLOW_SPOREBEAN)).offerTo(consumer, new Identifier(getRecipeName(ModItems.YELLOW_SPOREBEAN_BAG_3)));
        ShapelessRecipeJsonBuilder.create(RecipeCategory.MISC, ModItems.YELLOW_SPOREBEAN_BAG_2).input(ModItems.YELLOW_SPOREBEAN, 2).input(Items.PAPER, 1).criterion(hasItem(ModItems.YELLOW_SPOREBEAN), conditionsFromItem(ModItems.YELLOW_SPOREBEAN)).offerTo(consumer, new Identifier(getRecipeName(ModItems.YELLOW_SPOREBEAN_BAG_2)));
        ShapelessRecipeJsonBuilder.create(RecipeCategory.MISC, ModItems.GREEN_SPOREBEAN_BAG).input(ModItems.GREEN_SPOREBEAN, 8).input(Items.PAPER, 1).criterion(hasItem(ModItems.GREEN_SPOREBEAN), conditionsFromItem(ModItems.GREEN_SPOREBEAN)).offerTo(consumer, new Identifier(getRecipeName(ModItems.GREEN_SPOREBEAN_BAG)));
        ShapelessRecipeJsonBuilder.create(RecipeCategory.MISC, ModItems.GREEN_SPOREBEAN_BAG_7).input(ModItems.GREEN_SPOREBEAN, 7).input(Items.PAPER, 1).criterion(hasItem(ModItems.GREEN_SPOREBEAN), conditionsFromItem(ModItems.GREEN_SPOREBEAN)).offerTo(consumer, new Identifier(getRecipeName(ModItems.GREEN_SPOREBEAN_BAG_7)));
        ShapelessRecipeJsonBuilder.create(RecipeCategory.MISC, ModItems.GREEN_SPOREBEAN_BAG_6).input(ModItems.GREEN_SPOREBEAN, 6).input(Items.PAPER, 1).criterion(hasItem(ModItems.GREEN_SPOREBEAN), conditionsFromItem(ModItems.GREEN_SPOREBEAN)).offerTo(consumer, new Identifier(getRecipeName(ModItems.GREEN_SPOREBEAN_BAG_6)));
        ShapelessRecipeJsonBuilder.create(RecipeCategory.MISC, ModItems.GREEN_SPOREBEAN_BAG_5).input(ModItems.GREEN_SPOREBEAN, 5).input(Items.PAPER, 1).criterion(hasItem(ModItems.GREEN_SPOREBEAN), conditionsFromItem(ModItems.GREEN_SPOREBEAN)).offerTo(consumer, new Identifier(getRecipeName(ModItems.GREEN_SPOREBEAN_BAG_5)));
        ShapelessRecipeJsonBuilder.create(RecipeCategory.MISC, ModItems.GREEN_SPOREBEAN_BAG_4).input(ModItems.GREEN_SPOREBEAN, 4).input(Items.PAPER, 1).criterion(hasItem(ModItems.GREEN_SPOREBEAN), conditionsFromItem(ModItems.GREEN_SPOREBEAN)).offerTo(consumer, new Identifier(getRecipeName(ModItems.GREEN_SPOREBEAN_BAG_4)));
        ShapelessRecipeJsonBuilder.create(RecipeCategory.MISC, ModItems.GREEN_SPOREBEAN_BAG_3).input(ModItems.GREEN_SPOREBEAN, 3).input(Items.PAPER, 1).criterion(hasItem(ModItems.GREEN_SPOREBEAN), conditionsFromItem(ModItems.GREEN_SPOREBEAN)).offerTo(consumer, new Identifier(getRecipeName(ModItems.GREEN_SPOREBEAN_BAG_3)));
        ShapelessRecipeJsonBuilder.create(RecipeCategory.MISC, ModItems.GREEN_SPOREBEAN_BAG_2).input(ModItems.GREEN_SPOREBEAN, 2).input(Items.PAPER, 1).criterion(hasItem(ModItems.GREEN_SPOREBEAN), conditionsFromItem(ModItems.GREEN_SPOREBEAN)).offerTo(consumer, new Identifier(getRecipeName(ModItems.GREEN_SPOREBEAN_BAG_2)));
        ShapelessRecipeJsonBuilder.create(RecipeCategory.MISC, ModItems.BLUE_SPOREBEAN_BAG).input(ModItems.BLUE_SPOREBEAN, 8).input(Items.PAPER, 1).criterion(hasItem(ModItems.BLUE_SPOREBEAN), conditionsFromItem(ModItems.BLUE_SPOREBEAN)).offerTo(consumer, new Identifier(getRecipeName(ModItems.BLUE_SPOREBEAN_BAG)));
        ShapelessRecipeJsonBuilder.create(RecipeCategory.MISC, ModItems.BLUE_SPOREBEAN_BAG_7).input(ModItems.BLUE_SPOREBEAN, 7).input(Items.PAPER, 1).criterion(hasItem(ModItems.BLUE_SPOREBEAN), conditionsFromItem(ModItems.BLUE_SPOREBEAN)).offerTo(consumer, new Identifier(getRecipeName(ModItems.BLUE_SPOREBEAN_BAG_7)));
        ShapelessRecipeJsonBuilder.create(RecipeCategory.MISC, ModItems.BLUE_SPOREBEAN_BAG_6).input(ModItems.BLUE_SPOREBEAN, 6).input(Items.PAPER, 1).criterion(hasItem(ModItems.BLUE_SPOREBEAN), conditionsFromItem(ModItems.BLUE_SPOREBEAN)).offerTo(consumer, new Identifier(getRecipeName(ModItems.BLUE_SPOREBEAN_BAG_6)));
        ShapelessRecipeJsonBuilder.create(RecipeCategory.MISC, ModItems.BLUE_SPOREBEAN_BAG_5).input(ModItems.BLUE_SPOREBEAN, 5).input(Items.PAPER, 1).criterion(hasItem(ModItems.BLUE_SPOREBEAN), conditionsFromItem(ModItems.BLUE_SPOREBEAN)).offerTo(consumer, new Identifier(getRecipeName(ModItems.BLUE_SPOREBEAN_BAG_5)));
        ShapelessRecipeJsonBuilder.create(RecipeCategory.MISC, ModItems.BLUE_SPOREBEAN_BAG_4).input(ModItems.BLUE_SPOREBEAN, 4).input(Items.PAPER, 1).criterion(hasItem(ModItems.BLUE_SPOREBEAN), conditionsFromItem(ModItems.BLUE_SPOREBEAN)).offerTo(consumer, new Identifier(getRecipeName(ModItems.BLUE_SPOREBEAN_BAG_4)));
        ShapelessRecipeJsonBuilder.create(RecipeCategory.MISC, ModItems.BLUE_SPOREBEAN_BAG_3).input(ModItems.BLUE_SPOREBEAN, 3).input(Items.PAPER, 1).criterion(hasItem(ModItems.BLUE_SPOREBEAN), conditionsFromItem(ModItems.BLUE_SPOREBEAN)).offerTo(consumer, new Identifier(getRecipeName(ModItems.BLUE_SPOREBEAN_BAG_3)));
        ShapelessRecipeJsonBuilder.create(RecipeCategory.MISC, ModItems.BLUE_SPOREBEAN_BAG_2).input(ModItems.BLUE_SPOREBEAN, 2).input(Items.PAPER, 1).criterion(hasItem(ModItems.BLUE_SPOREBEAN), conditionsFromItem(ModItems.BLUE_SPOREBEAN)).offerTo(consumer, new Identifier(getRecipeName(ModItems.BLUE_SPOREBEAN_BAG_2)));
        ShapelessRecipeJsonBuilder.create(RecipeCategory.MISC, ModItems.PURPLE_SPOREBEAN_BAG).input(ModItems.PURPLE_SPOREBEAN, 8).input(Items.PAPER, 1).criterion(hasItem(ModItems.PURPLE_SPOREBEAN), conditionsFromItem(ModItems.PURPLE_SPOREBEAN)).offerTo(consumer, new Identifier(getRecipeName(ModItems.PURPLE_SPOREBEAN_BAG)));
        ShapelessRecipeJsonBuilder.create(RecipeCategory.MISC, ModItems.PURPLE_SPOREBEAN_BAG_7).input(ModItems.PURPLE_SPOREBEAN, 7).input(Items.PAPER, 1).criterion(hasItem(ModItems.PURPLE_SPOREBEAN), conditionsFromItem(ModItems.PURPLE_SPOREBEAN)).offerTo(consumer, new Identifier(getRecipeName(ModItems.PURPLE_SPOREBEAN_BAG_7)));
        ShapelessRecipeJsonBuilder.create(RecipeCategory.MISC, ModItems.PURPLE_SPOREBEAN_BAG_6).input(ModItems.PURPLE_SPOREBEAN, 6).input(Items.PAPER, 1).criterion(hasItem(ModItems.PURPLE_SPOREBEAN), conditionsFromItem(ModItems.PURPLE_SPOREBEAN)).offerTo(consumer, new Identifier(getRecipeName(ModItems.PURPLE_SPOREBEAN_BAG_6)));
        ShapelessRecipeJsonBuilder.create(RecipeCategory.MISC, ModItems.PURPLE_SPOREBEAN_BAG_5).input(ModItems.PURPLE_SPOREBEAN, 5).input(Items.PAPER, 1).criterion(hasItem(ModItems.PURPLE_SPOREBEAN), conditionsFromItem(ModItems.PURPLE_SPOREBEAN)).offerTo(consumer, new Identifier(getRecipeName(ModItems.PURPLE_SPOREBEAN_BAG_5)));
        ShapelessRecipeJsonBuilder.create(RecipeCategory.MISC, ModItems.PURPLE_SPOREBEAN_BAG_4).input(ModItems.PURPLE_SPOREBEAN, 4).input(Items.PAPER, 1).criterion(hasItem(ModItems.PURPLE_SPOREBEAN), conditionsFromItem(ModItems.PURPLE_SPOREBEAN)).offerTo(consumer, new Identifier(getRecipeName(ModItems.PURPLE_SPOREBEAN_BAG_4)));
        ShapelessRecipeJsonBuilder.create(RecipeCategory.MISC, ModItems.PURPLE_SPOREBEAN_BAG_3).input(ModItems.PURPLE_SPOREBEAN, 3).input(Items.PAPER, 1).criterion(hasItem(ModItems.PURPLE_SPOREBEAN), conditionsFromItem(ModItems.PURPLE_SPOREBEAN)).offerTo(consumer, new Identifier(getRecipeName(ModItems.PURPLE_SPOREBEAN_BAG_3)));
        ShapelessRecipeJsonBuilder.create(RecipeCategory.MISC, ModItems.PURPLE_SPOREBEAN_BAG_2).input(ModItems.PURPLE_SPOREBEAN, 2).input(Items.PAPER, 1).criterion(hasItem(ModItems.PURPLE_SPOREBEAN), conditionsFromItem(ModItems.PURPLE_SPOREBEAN)).offerTo(consumer, new Identifier(getRecipeName(ModItems.PURPLE_SPOREBEAN_BAG_2)));
        ShapelessRecipeJsonBuilder.create(RecipeCategory.MISC, ModItems.GRAY_SPOREBEAN_BAG).input(ModItems.GRAY_SPOREBEAN, 8).input(Items.PAPER, 1).criterion(hasItem(ModItems.GRAY_SPOREBEAN), conditionsFromItem(ModItems.GRAY_SPOREBEAN)).offerTo(consumer, new Identifier(getRecipeName(ModItems.GRAY_SPOREBEAN_BAG)));
        ShapelessRecipeJsonBuilder.create(RecipeCategory.MISC, ModItems.GRAY_SPOREBEAN_BAG_7).input(ModItems.GRAY_SPOREBEAN, 7).input(Items.PAPER, 1).criterion(hasItem(ModItems.GRAY_SPOREBEAN), conditionsFromItem(ModItems.GRAY_SPOREBEAN)).offerTo(consumer, new Identifier(getRecipeName(ModItems.GRAY_SPOREBEAN_BAG_7)));
        ShapelessRecipeJsonBuilder.create(RecipeCategory.MISC, ModItems.GRAY_SPOREBEAN_BAG_6).input(ModItems.GRAY_SPOREBEAN, 6).input(Items.PAPER, 1).criterion(hasItem(ModItems.GRAY_SPOREBEAN), conditionsFromItem(ModItems.GRAY_SPOREBEAN)).offerTo(consumer, new Identifier(getRecipeName(ModItems.GRAY_SPOREBEAN_BAG_6)));
        ShapelessRecipeJsonBuilder.create(RecipeCategory.MISC, ModItems.GRAY_SPOREBEAN_BAG_5).input(ModItems.GRAY_SPOREBEAN, 5).input(Items.PAPER, 1).criterion(hasItem(ModItems.GRAY_SPOREBEAN), conditionsFromItem(ModItems.GRAY_SPOREBEAN)).offerTo(consumer, new Identifier(getRecipeName(ModItems.GRAY_SPOREBEAN_BAG_5)));
        ShapelessRecipeJsonBuilder.create(RecipeCategory.MISC, ModItems.GRAY_SPOREBEAN_BAG_4).input(ModItems.GRAY_SPOREBEAN, 4).input(Items.PAPER, 1).criterion(hasItem(ModItems.GRAY_SPOREBEAN), conditionsFromItem(ModItems.GRAY_SPOREBEAN)).offerTo(consumer, new Identifier(getRecipeName(ModItems.GRAY_SPOREBEAN_BAG_4)));
        ShapelessRecipeJsonBuilder.create(RecipeCategory.MISC, ModItems.GRAY_SPOREBEAN_BAG_3).input(ModItems.GRAY_SPOREBEAN, 3).input(Items.PAPER, 1).criterion(hasItem(ModItems.GRAY_SPOREBEAN), conditionsFromItem(ModItems.GRAY_SPOREBEAN)).offerTo(consumer, new Identifier(getRecipeName(ModItems.GRAY_SPOREBEAN_BAG_3)));
        ShapelessRecipeJsonBuilder.create(RecipeCategory.MISC, ModItems.GRAY_SPOREBEAN_BAG_2).input(ModItems.GRAY_SPOREBEAN, 2).input(Items.PAPER, 1).criterion(hasItem(ModItems.GRAY_SPOREBEAN), conditionsFromItem(ModItems.GRAY_SPOREBEAN)).offerTo(consumer, new Identifier(getRecipeName(ModItems.GRAY_SPOREBEAN_BAG_2)));
    }
}
