package net.sadmush.effectbeans.datagen;

import net.fabricmc.fabric.api.datagen.v1.FabricDataOutput;
import net.fabricmc.fabric.api.datagen.v1.provider.FabricRecipeProvider;
import net.minecraft.block.Blocks;
import net.minecraft.data.server.recipe.RecipeJsonProvider;
import net.minecraft.data.server.recipe.ShapedRecipeJsonBuilder;
import net.minecraft.data.server.recipe.ShapelessRecipeJsonBuilder;
import net.minecraft.item.ItemConvertible;
import net.minecraft.item.Items;
import net.minecraft.recipe.book.RecipeCategory;
import net.minecraft.util.Identifier;
import net.sadmush.effectbeans.block.ModBlocks;
import net.sadmush.effectbeans.item.ModItems;
import net.sadmush.effectbeans.util.ModTags;

import java.util.List;
import java.util.function.Consumer;

public class ModRecipeProvider extends FabricRecipeProvider {

    public ModRecipeProvider(FabricDataOutput output) {
        super(output);
    }

    @Override
    public void generate(Consumer<RecipeJsonProvider> consumer) {
        ShapedRecipeJsonBuilder.create(RecipeCategory.FOOD, ModItems.SPOREBEAN).input('+', Items.SUGAR).input('#', Items.GLOW_BERRIES).pattern(" + ").pattern("+#+").pattern(" + ").criterion(hasItem(Items.GLOW_BERRIES), conditionsFromItem(Items.GLOW_BERRIES)).group("spore").offerTo(consumer, new Identifier(getRecipeName(ModItems.SPOREBEAN)));
        ShapelessRecipeJsonBuilder.create(RecipeCategory.FOOD, ModItems.RED_SPOREBEAN).input(ModTags.Items.SPOREBEANS).input(Items.RED_DYE, 1).criterion(hasItem(ModItems.SPOREBEAN), conditionsFromItem(ModItems.SPOREBEAN)).group("spore").offerTo(consumer, new Identifier(getRecipeName(ModItems.RED_SPOREBEAN)));
        ShapelessRecipeJsonBuilder.create(RecipeCategory.FOOD, ModItems.YELLOW_SPOREBEAN).input(ModTags.Items.SPOREBEANS).input(Items.YELLOW_DYE, 1).criterion(hasItem(ModItems.SPOREBEAN), conditionsFromItem(ModItems.SPOREBEAN)).group("spore").offerTo(consumer, new Identifier(getRecipeName(ModItems.YELLOW_SPOREBEAN)));
        ShapelessRecipeJsonBuilder.create(RecipeCategory.FOOD, ModItems.GREEN_SPOREBEAN).input(ModTags.Items.SPOREBEANS).input(Items.GREEN_DYE, 1).criterion(hasItem(ModItems.SPOREBEAN), conditionsFromItem(ModItems.SPOREBEAN)).group("spore").offerTo(consumer, new Identifier(getRecipeName(ModItems.GREEN_SPOREBEAN)));
        ShapelessRecipeJsonBuilder.create(RecipeCategory.FOOD, ModItems.BLUE_SPOREBEAN).input(ModTags.Items.SPOREBEANS).input(Items.BLUE_DYE, 1).criterion(hasItem(ModItems.SPOREBEAN), conditionsFromItem(ModItems.SPOREBEAN)).group("spore").offerTo(consumer, new Identifier(getRecipeName(ModItems.BLUE_SPOREBEAN)));
        ShapelessRecipeJsonBuilder.create(RecipeCategory.FOOD, ModItems.PURPLE_SPOREBEAN).input(ModTags.Items.SPOREBEANS).input(Items.PURPLE_DYE, 1).criterion(hasItem(ModItems.SPOREBEAN), conditionsFromItem(ModItems.SPOREBEAN)).group("spore").offerTo(consumer, new Identifier(getRecipeName(ModItems.PURPLE_SPOREBEAN)));
        ShapelessRecipeJsonBuilder.create(RecipeCategory.FOOD, ModItems.GRAY_SPOREBEAN).input(ModTags.Items.SPOREBEANS).input(Items.GRAY_DYE, 1).criterion(hasItem(ModItems.SPOREBEAN), conditionsFromItem(ModItems.SPOREBEAN)).group("spore").offerTo(consumer, new Identifier(getRecipeName(ModItems.GRAY_SPOREBEAN)));
        ShapelessRecipeJsonBuilder.create(RecipeCategory.FOOD, ModItems.WHITE_SPOREBEAN).input(ModTags.Items.SPOREBEANS).input(Items.WHITE_DYE, 1).criterion(hasItem(ModItems.SPOREBEAN), conditionsFromItem(ModItems.SPOREBEAN)).group("spore").offerTo(consumer, new Identifier(getRecipeName(ModItems.WHITE_SPOREBEAN)));
        ShapelessRecipeJsonBuilder.create(RecipeCategory.FOOD, ModItems.PINK_SPOREBEAN).input(ModTags.Items.SPOREBEANS).input(Items.PINK_DYE, 1).criterion(hasItem(ModItems.SPOREBEAN), conditionsFromItem(ModItems.SPOREBEAN)).group("spore").offerTo(consumer, new Identifier(getRecipeName(ModItems.PINK_SPOREBEAN)));
        ShapelessRecipeJsonBuilder.create(RecipeCategory.FOOD, ModItems.ORANGE_SPOREBEAN).input(ModTags.Items.SPOREBEANS).input(Items.ORANGE_DYE, 1).criterion(hasItem(ModItems.SPOREBEAN), conditionsFromItem(ModItems.SPOREBEAN)).group("spore").offerTo(consumer, new Identifier(getRecipeName(ModItems.ORANGE_SPOREBEAN)));
        ShapelessRecipeJsonBuilder.create(RecipeCategory.MISC, ModItems.SPOREBEAN_BAG).input(ModItems.SPOREBEAN, 8).input(Items.PAPER, 1).criterion(hasItem(ModItems.SPOREBEAN), conditionsFromItem(ModItems.SPOREBEAN)).offerTo(consumer, new Identifier(getRecipeName(ModItems.SPOREBEAN_BAG)));
        ShapelessRecipeJsonBuilder.create(RecipeCategory.MISC, ModItems.SPOREBEAN_BAG_7).input(ModItems.SPOREBEAN, 7).input(Items.PAPER, 1).criterion(hasItem(ModItems.SPOREBEAN), conditionsFromItem(ModItems.SPOREBEAN)).offerTo(consumer, new Identifier(getRecipeName(ModItems.SPOREBEAN_BAG_7)));
        ShapelessRecipeJsonBuilder.create(RecipeCategory.MISC, ModItems.SPOREBEAN_BAG_6).input(ModItems.SPOREBEAN, 6).input(Items.PAPER, 1).criterion(hasItem(ModItems.SPOREBEAN), conditionsFromItem(ModItems.SPOREBEAN)).offerTo(consumer, new Identifier(getRecipeName(ModItems.SPOREBEAN_BAG_6)));
        ShapelessRecipeJsonBuilder.create(RecipeCategory.MISC, ModItems.SPOREBEAN_BAG_5).input(ModItems.SPOREBEAN, 5).input(Items.PAPER, 1).criterion(hasItem(ModItems.SPOREBEAN), conditionsFromItem(ModItems.SPOREBEAN)).offerTo(consumer, new Identifier(getRecipeName(ModItems.SPOREBEAN_BAG_5)));
        ShapelessRecipeJsonBuilder.create(RecipeCategory.MISC, ModItems.SPOREBEAN_BAG_4).input(ModItems.SPOREBEAN, 4).input(Items.PAPER, 1).criterion(hasItem(ModItems.SPOREBEAN), conditionsFromItem(ModItems.SPOREBEAN)).offerTo(consumer, new Identifier(getRecipeName(ModItems.SPOREBEAN_BAG_4)));
        ShapelessRecipeJsonBuilder.create(RecipeCategory.MISC, ModItems.SPOREBEAN_BAG_3).input(ModItems.SPOREBEAN, 3).input(Items.PAPER, 1).criterion(hasItem(ModItems.SPOREBEAN), conditionsFromItem(ModItems.SPOREBEAN)).offerTo(consumer, new Identifier(getRecipeName(ModItems.SPOREBEAN_BAG_3)));
        ShapelessRecipeJsonBuilder.create(RecipeCategory.MISC, ModItems.SPOREBEAN_BAG_2).input(ModItems.SPOREBEAN, 2).input(Items.PAPER, 1).criterion(hasItem(ModItems.SPOREBEAN), conditionsFromItem(ModItems.SPOREBEAN)).offerTo(consumer, new Identifier(getRecipeName(ModItems.SPOREBEAN_BAG_2)));
        ShapelessRecipeJsonBuilder.create(RecipeCategory.MISC, ModItems.RED_SPOREBEAN_BAG).input(ModItems.RED_SPOREBEAN, 8).input(Items.PAPER, 1).criterion(hasItem(ModItems.RED_SPOREBEAN), conditionsFromItem(ModItems.RED_SPOREBEAN)).offerTo(consumer, new Identifier(getRecipeName(ModItems.RED_SPOREBEAN_BAG)));
        ShapelessRecipeJsonBuilder.create(RecipeCategory.MISC, ModItems.RED_SPOREBEAN_BAG_7).input(ModItems.RED_SPOREBEAN, 7).input(Items.PAPER, 1).criterion(hasItem(ModItems.RED_SPOREBEAN), conditionsFromItem(ModItems.RED_SPOREBEAN)).offerTo(consumer, new Identifier(getRecipeName(ModItems.RED_SPOREBEAN_BAG_7)));
        ShapelessRecipeJsonBuilder.create(RecipeCategory.MISC, ModItems.RED_SPOREBEAN_BAG_6).input(ModItems.RED_SPOREBEAN, 6).input(Items.PAPER, 1).criterion(hasItem(ModItems.RED_SPOREBEAN), conditionsFromItem(ModItems.RED_SPOREBEAN)).offerTo(consumer, new Identifier(getRecipeName(ModItems.RED_SPOREBEAN_BAG_6)));
        ShapelessRecipeJsonBuilder.create(RecipeCategory.MISC, ModItems.RED_SPOREBEAN_BAG_5).input(ModItems.RED_SPOREBEAN, 5).input(Items.PAPER, 1).criterion(hasItem(ModItems.RED_SPOREBEAN), conditionsFromItem(ModItems.RED_SPOREBEAN)).offerTo(consumer, new Identifier(getRecipeName(ModItems.RED_SPOREBEAN_BAG_5)));
        ShapelessRecipeJsonBuilder.create(RecipeCategory.MISC, ModItems.RED_SPOREBEAN_BAG_4).input(ModItems.RED_SPOREBEAN, 4).input(Items.PAPER, 1).criterion(hasItem(ModItems.RED_SPOREBEAN), conditionsFromItem(ModItems.RED_SPOREBEAN)).offerTo(consumer, new Identifier(getRecipeName(ModItems.RED_SPOREBEAN_BAG_4)));
        ShapelessRecipeJsonBuilder.create(RecipeCategory.MISC, ModItems.RED_SPOREBEAN_BAG_3).input(ModItems.RED_SPOREBEAN, 3).input(Items.PAPER, 1).criterion(hasItem(ModItems.RED_SPOREBEAN), conditionsFromItem(ModItems.RED_SPOREBEAN)).offerTo(consumer, new Identifier(getRecipeName(ModItems.RED_SPOREBEAN_BAG_3)));
        ShapelessRecipeJsonBuilder.create(RecipeCategory.MISC, ModItems.RED_SPOREBEAN_BAG_2).input(ModItems.RED_SPOREBEAN, 2).input(Items.PAPER, 1).criterion(hasItem(ModItems.RED_SPOREBEAN), conditionsFromItem(ModItems.RED_SPOREBEAN)).offerTo(consumer, new Identifier(getRecipeName(ModItems.RED_SPOREBEAN_BAG_2)));
        ShapelessRecipeJsonBuilder.create(RecipeCategory.MISC, ModItems.YELLOW_SPOREBEAN_BAG).input(ModItems.YELLOW_SPOREBEAN, 8).input(Items.PAPER, 1).criterion(hasItem(ModItems.YELLOW_SPOREBEAN), conditionsFromItem(ModItems.YELLOW_SPOREBEAN)).offerTo(consumer, new Identifier(getRecipeName(ModItems.YELLOW_SPOREBEAN_BAG)));
        ShapelessRecipeJsonBuilder.create(RecipeCategory.MISC, ModItems.YELLOW_SPOREBEAN_BAG_7).input(ModItems.YELLOW_SPOREBEAN, 7).input(Items.PAPER, 1).criterion(hasItem(ModItems.YELLOW_SPOREBEAN), conditionsFromItem(ModItems.YELLOW_SPOREBEAN)).offerTo(consumer, new Identifier(getRecipeName(ModItems.YELLOW_SPOREBEAN_BAG_7)));
        ShapelessRecipeJsonBuilder.create(RecipeCategory.MISC, ModItems.YELLOW_SPOREBEAN_BAG_6).input(ModItems.YELLOW_SPOREBEAN, 6).input(Items.PAPER, 1).criterion(hasItem(ModItems.YELLOW_SPOREBEAN), conditionsFromItem(ModItems.YELLOW_SPOREBEAN)).offerTo(consumer, new Identifier(getRecipeName(ModItems.YELLOW_SPOREBEAN_BAG_6)));
        ShapelessRecipeJsonBuilder.create(RecipeCategory.MISC, ModItems.YELLOW_SPOREBEAN_BAG_5).input(ModItems.YELLOW_SPOREBEAN, 5).input(Items.PAPER, 1).criterion(hasItem(ModItems.YELLOW_SPOREBEAN), conditionsFromItem(ModItems.YELLOW_SPOREBEAN)).offerTo(consumer, new Identifier(getRecipeName(ModItems.YELLOW_SPOREBEAN_BAG_5)));
        ShapelessRecipeJsonBuilder.create(RecipeCategory.MISC, ModItems.YELLOW_SPOREBEAN_BAG_4).input(ModItems.YELLOW_SPOREBEAN, 4).input(Items.PAPER, 1).criterion(hasItem(ModItems.YELLOW_SPOREBEAN), conditionsFromItem(ModItems.YELLOW_SPOREBEAN)).offerTo(consumer, new Identifier(getRecipeName(ModItems.YELLOW_SPOREBEAN_BAG_4)));
        ShapelessRecipeJsonBuilder.create(RecipeCategory.MISC, ModItems.YELLOW_SPOREBEAN_BAG_3).input(ModItems.YELLOW_SPOREBEAN, 3).input(Items.PAPER, 1).criterion(hasItem(ModItems.YELLOW_SPOREBEAN), conditionsFromItem(ModItems.YELLOW_SPOREBEAN)).offerTo(consumer, new Identifier(getRecipeName(ModItems.YELLOW_SPOREBEAN_BAG_3)));
        ShapelessRecipeJsonBuilder.create(RecipeCategory.MISC, ModItems.YELLOW_SPOREBEAN_BAG_2).input(ModItems.YELLOW_SPOREBEAN, 2).input(Items.PAPER, 1).criterion(hasItem(ModItems.YELLOW_SPOREBEAN), conditionsFromItem(ModItems.YELLOW_SPOREBEAN)).offerTo(consumer, new Identifier(getRecipeName(ModItems.YELLOW_SPOREBEAN_BAG_2)));
        ShapelessRecipeJsonBuilder.create(RecipeCategory.MISC, ModItems.GREEN_SPOREBEAN_BAG).input(ModItems.GREEN_SPOREBEAN, 8).input(Items.PAPER, 1).criterion(hasItem(ModItems.GREEN_SPOREBEAN), conditionsFromItem(ModItems.GREEN_SPOREBEAN)).offerTo(consumer, new Identifier(getRecipeName(ModItems.GREEN_SPOREBEAN_BAG)));
        ShapelessRecipeJsonBuilder.create(RecipeCategory.MISC, ModItems.GREEN_SPOREBEAN_BAG_7).input(ModItems.GREEN_SPOREBEAN, 7).input(Items.PAPER, 1).criterion(hasItem(ModItems.GREEN_SPOREBEAN), conditionsFromItem(ModItems.GREEN_SPOREBEAN)).offerTo(consumer, new Identifier(getRecipeName(ModItems.GREEN_SPOREBEAN_BAG_7)));
        ShapelessRecipeJsonBuilder.create(RecipeCategory.MISC, ModItems.GREEN_SPOREBEAN_BAG_6).input(ModItems.GREEN_SPOREBEAN, 6).input(Items.PAPER, 1).criterion(hasItem(ModItems.GREEN_SPOREBEAN), conditionsFromItem(ModItems.GREEN_SPOREBEAN)).offerTo(consumer, new Identifier(getRecipeName(ModItems.GREEN_SPOREBEAN_BAG_6)));
        ShapelessRecipeJsonBuilder.create(RecipeCategory.MISC, ModItems.GREEN_SPOREBEAN_BAG_5).input(ModItems.GREEN_SPOREBEAN, 5).input(Items.PAPER, 1).criterion(hasItem(ModItems.GREEN_SPOREBEAN), conditionsFromItem(ModItems.GREEN_SPOREBEAN)).offerTo(consumer, new Identifier(getRecipeName(ModItems.GREEN_SPOREBEAN_BAG_5)));
        ShapelessRecipeJsonBuilder.create(RecipeCategory.MISC, ModItems.GREEN_SPOREBEAN_BAG_4).input(ModItems.GREEN_SPOREBEAN, 4).input(Items.PAPER, 1).criterion(hasItem(ModItems.GREEN_SPOREBEAN), conditionsFromItem(ModItems.GREEN_SPOREBEAN)).offerTo(consumer, new Identifier(getRecipeName(ModItems.GREEN_SPOREBEAN_BAG_4)));
        ShapelessRecipeJsonBuilder.create(RecipeCategory.MISC, ModItems.GREEN_SPOREBEAN_BAG_3).input(ModItems.GREEN_SPOREBEAN, 3).input(Items.PAPER, 1).criterion(hasItem(ModItems.GREEN_SPOREBEAN), conditionsFromItem(ModItems.GREEN_SPOREBEAN)).offerTo(consumer, new Identifier(getRecipeName(ModItems.GREEN_SPOREBEAN_BAG_3)));
        ShapelessRecipeJsonBuilder.create(RecipeCategory.MISC, ModItems.GREEN_SPOREBEAN_BAG_2).input(ModItems.GREEN_SPOREBEAN, 2).input(Items.PAPER, 1).criterion(hasItem(ModItems.GREEN_SPOREBEAN), conditionsFromItem(ModItems.GREEN_SPOREBEAN)).offerTo(consumer, new Identifier(getRecipeName(ModItems.GREEN_SPOREBEAN_BAG_2)));
        ShapelessRecipeJsonBuilder.create(RecipeCategory.MISC, ModItems.BLUE_SPOREBEAN_BAG).input(ModItems.BLUE_SPOREBEAN, 8).input(Items.PAPER, 1).criterion(hasItem(ModItems.BLUE_SPOREBEAN), conditionsFromItem(ModItems.BLUE_SPOREBEAN)).offerTo(consumer, new Identifier(getRecipeName(ModItems.BLUE_SPOREBEAN_BAG)));
        ShapelessRecipeJsonBuilder.create(RecipeCategory.MISC, ModItems.BLUE_SPOREBEAN_BAG_7).input(ModItems.BLUE_SPOREBEAN, 7).input(Items.PAPER, 1).criterion(hasItem(ModItems.BLUE_SPOREBEAN), conditionsFromItem(ModItems.BLUE_SPOREBEAN)).offerTo(consumer, new Identifier(getRecipeName(ModItems.BLUE_SPOREBEAN_BAG_7)));
        ShapelessRecipeJsonBuilder.create(RecipeCategory.MISC, ModItems.BLUE_SPOREBEAN_BAG_6).input(ModItems.BLUE_SPOREBEAN, 6).input(Items.PAPER, 1).criterion(hasItem(ModItems.BLUE_SPOREBEAN), conditionsFromItem(ModItems.BLUE_SPOREBEAN)).offerTo(consumer, new Identifier(getRecipeName(ModItems.BLUE_SPOREBEAN_BAG_6)));
        ShapelessRecipeJsonBuilder.create(RecipeCategory.MISC, ModItems.BLUE_SPOREBEAN_BAG_5).input(ModItems.BLUE_SPOREBEAN, 5).input(Items.PAPER, 1).criterion(hasItem(ModItems.BLUE_SPOREBEAN), conditionsFromItem(ModItems.BLUE_SPOREBEAN)).offerTo(consumer, new Identifier(getRecipeName(ModItems.BLUE_SPOREBEAN_BAG_5)));
        ShapelessRecipeJsonBuilder.create(RecipeCategory.MISC, ModItems.BLUE_SPOREBEAN_BAG_4).input(ModItems.BLUE_SPOREBEAN, 4).input(Items.PAPER, 1).criterion(hasItem(ModItems.BLUE_SPOREBEAN), conditionsFromItem(ModItems.BLUE_SPOREBEAN)).offerTo(consumer, new Identifier(getRecipeName(ModItems.BLUE_SPOREBEAN_BAG_4)));
        ShapelessRecipeJsonBuilder.create(RecipeCategory.MISC, ModItems.BLUE_SPOREBEAN_BAG_3).input(ModItems.BLUE_SPOREBEAN, 3).input(Items.PAPER, 1).criterion(hasItem(ModItems.BLUE_SPOREBEAN), conditionsFromItem(ModItems.BLUE_SPOREBEAN)).offerTo(consumer, new Identifier(getRecipeName(ModItems.BLUE_SPOREBEAN_BAG_3)));
        ShapelessRecipeJsonBuilder.create(RecipeCategory.MISC, ModItems.BLUE_SPOREBEAN_BAG_2).input(ModItems.BLUE_SPOREBEAN, 2).input(Items.PAPER, 1).criterion(hasItem(ModItems.BLUE_SPOREBEAN), conditionsFromItem(ModItems.BLUE_SPOREBEAN)).offerTo(consumer, new Identifier(getRecipeName(ModItems.BLUE_SPOREBEAN_BAG_2)));
        ShapelessRecipeJsonBuilder.create(RecipeCategory.MISC, ModItems.PURPLE_SPOREBEAN_BAG).input(ModItems.PURPLE_SPOREBEAN, 8).input(Items.PAPER, 1).criterion(hasItem(ModItems.PURPLE_SPOREBEAN), conditionsFromItem(ModItems.PURPLE_SPOREBEAN)).offerTo(consumer, new Identifier(getRecipeName(ModItems.PURPLE_SPOREBEAN_BAG)));
        ShapelessRecipeJsonBuilder.create(RecipeCategory.MISC, ModItems.PURPLE_SPOREBEAN_BAG_7).input(ModItems.PURPLE_SPOREBEAN, 7).input(Items.PAPER, 1).criterion(hasItem(ModItems.PURPLE_SPOREBEAN), conditionsFromItem(ModItems.PURPLE_SPOREBEAN)).offerTo(consumer, new Identifier(getRecipeName(ModItems.PURPLE_SPOREBEAN_BAG_7)));
        ShapelessRecipeJsonBuilder.create(RecipeCategory.MISC, ModItems.PURPLE_SPOREBEAN_BAG_6).input(ModItems.PURPLE_SPOREBEAN, 6).input(Items.PAPER, 1).criterion(hasItem(ModItems.PURPLE_SPOREBEAN), conditionsFromItem(ModItems.PURPLE_SPOREBEAN)).offerTo(consumer, new Identifier(getRecipeName(ModItems.PURPLE_SPOREBEAN_BAG_6)));
        ShapelessRecipeJsonBuilder.create(RecipeCategory.MISC, ModItems.PURPLE_SPOREBEAN_BAG_5).input(ModItems.PURPLE_SPOREBEAN, 5).input(Items.PAPER, 1).criterion(hasItem(ModItems.PURPLE_SPOREBEAN), conditionsFromItem(ModItems.PURPLE_SPOREBEAN)).offerTo(consumer, new Identifier(getRecipeName(ModItems.PURPLE_SPOREBEAN_BAG_5)));
        ShapelessRecipeJsonBuilder.create(RecipeCategory.MISC, ModItems.PURPLE_SPOREBEAN_BAG_4).input(ModItems.PURPLE_SPOREBEAN, 4).input(Items.PAPER, 1).criterion(hasItem(ModItems.PURPLE_SPOREBEAN), conditionsFromItem(ModItems.PURPLE_SPOREBEAN)).offerTo(consumer, new Identifier(getRecipeName(ModItems.PURPLE_SPOREBEAN_BAG_4)));
        ShapelessRecipeJsonBuilder.create(RecipeCategory.MISC, ModItems.PURPLE_SPOREBEAN_BAG_3).input(ModItems.PURPLE_SPOREBEAN, 3).input(Items.PAPER, 1).criterion(hasItem(ModItems.PURPLE_SPOREBEAN), conditionsFromItem(ModItems.PURPLE_SPOREBEAN)).offerTo(consumer, new Identifier(getRecipeName(ModItems.PURPLE_SPOREBEAN_BAG_3)));
        ShapelessRecipeJsonBuilder.create(RecipeCategory.MISC, ModItems.PURPLE_SPOREBEAN_BAG_2).input(ModItems.PURPLE_SPOREBEAN, 2).input(Items.PAPER, 1).criterion(hasItem(ModItems.PURPLE_SPOREBEAN), conditionsFromItem(ModItems.PURPLE_SPOREBEAN)).offerTo(consumer, new Identifier(getRecipeName(ModItems.PURPLE_SPOREBEAN_BAG_2)));
        ShapelessRecipeJsonBuilder.create(RecipeCategory.MISC, ModItems.GRAY_SPOREBEAN_BAG).input(ModItems.GRAY_SPOREBEAN, 8).input(Items.PAPER, 1).criterion(hasItem(ModItems.GRAY_SPOREBEAN), conditionsFromItem(ModItems.GRAY_SPOREBEAN)).offerTo(consumer, new Identifier(getRecipeName(ModItems.GRAY_SPOREBEAN_BAG)));
        ShapelessRecipeJsonBuilder.create(RecipeCategory.MISC, ModItems.GRAY_SPOREBEAN_BAG_7).input(ModItems.GRAY_SPOREBEAN, 7).input(Items.PAPER, 1).criterion(hasItem(ModItems.GRAY_SPOREBEAN), conditionsFromItem(ModItems.GRAY_SPOREBEAN)).offerTo(consumer, new Identifier(getRecipeName(ModItems.GRAY_SPOREBEAN_BAG_7)));
        ShapelessRecipeJsonBuilder.create(RecipeCategory.MISC, ModItems.GRAY_SPOREBEAN_BAG_6).input(ModItems.GRAY_SPOREBEAN, 6).input(Items.PAPER, 1).criterion(hasItem(ModItems.GRAY_SPOREBEAN), conditionsFromItem(ModItems.GRAY_SPOREBEAN)).offerTo(consumer, new Identifier(getRecipeName(ModItems.GRAY_SPOREBEAN_BAG_6)));
        ShapelessRecipeJsonBuilder.create(RecipeCategory.MISC, ModItems.GRAY_SPOREBEAN_BAG_5).input(ModItems.GRAY_SPOREBEAN, 5).input(Items.PAPER, 1).criterion(hasItem(ModItems.GRAY_SPOREBEAN), conditionsFromItem(ModItems.GRAY_SPOREBEAN)).offerTo(consumer, new Identifier(getRecipeName(ModItems.GRAY_SPOREBEAN_BAG_5)));
        ShapelessRecipeJsonBuilder.create(RecipeCategory.MISC, ModItems.GRAY_SPOREBEAN_BAG_4).input(ModItems.GRAY_SPOREBEAN, 4).input(Items.PAPER, 1).criterion(hasItem(ModItems.GRAY_SPOREBEAN), conditionsFromItem(ModItems.GRAY_SPOREBEAN)).offerTo(consumer, new Identifier(getRecipeName(ModItems.GRAY_SPOREBEAN_BAG_4)));
        ShapelessRecipeJsonBuilder.create(RecipeCategory.MISC, ModItems.GRAY_SPOREBEAN_BAG_3).input(ModItems.GRAY_SPOREBEAN, 3).input(Items.PAPER, 1).criterion(hasItem(ModItems.GRAY_SPOREBEAN), conditionsFromItem(ModItems.GRAY_SPOREBEAN)).offerTo(consumer, new Identifier(getRecipeName(ModItems.GRAY_SPOREBEAN_BAG_3)));
        ShapelessRecipeJsonBuilder.create(RecipeCategory.MISC, ModItems.GRAY_SPOREBEAN_BAG_2).input(ModItems.GRAY_SPOREBEAN, 2).input(Items.PAPER, 1).criterion(hasItem(ModItems.GRAY_SPOREBEAN), conditionsFromItem(ModItems.GRAY_SPOREBEAN)).offerTo(consumer, new Identifier(getRecipeName(ModItems.GRAY_SPOREBEAN_BAG_2)));
        ShapelessRecipeJsonBuilder.create(RecipeCategory.MISC, ModItems.PINK_SPOREBEAN_BAG).input(ModItems.PINK_SPOREBEAN, 8).input(Items.PAPER, 1).criterion(hasItem(ModItems.PINK_SPOREBEAN), conditionsFromItem(ModItems.PINK_SPOREBEAN)).offerTo(consumer, new Identifier(getRecipeName(ModItems.PINK_SPOREBEAN_BAG)));
        ShapelessRecipeJsonBuilder.create(RecipeCategory.MISC, ModItems.PINK_SPOREBEAN_BAG_7).input(ModItems.PINK_SPOREBEAN, 7).input(Items.PAPER, 1).criterion(hasItem(ModItems.PINK_SPOREBEAN), conditionsFromItem(ModItems.PINK_SPOREBEAN)).offerTo(consumer, new Identifier(getRecipeName(ModItems.PINK_SPOREBEAN_BAG_7)));
        ShapelessRecipeJsonBuilder.create(RecipeCategory.MISC, ModItems.PINK_SPOREBEAN_BAG_6).input(ModItems.PINK_SPOREBEAN, 6).input(Items.PAPER, 1).criterion(hasItem(ModItems.PINK_SPOREBEAN), conditionsFromItem(ModItems.PINK_SPOREBEAN)).offerTo(consumer, new Identifier(getRecipeName(ModItems.PINK_SPOREBEAN_BAG_6)));
        ShapelessRecipeJsonBuilder.create(RecipeCategory.MISC, ModItems.PINK_SPOREBEAN_BAG_5).input(ModItems.PINK_SPOREBEAN, 5).input(Items.PAPER, 1).criterion(hasItem(ModItems.PINK_SPOREBEAN), conditionsFromItem(ModItems.PINK_SPOREBEAN)).offerTo(consumer, new Identifier(getRecipeName(ModItems.PINK_SPOREBEAN_BAG_5)));
        ShapelessRecipeJsonBuilder.create(RecipeCategory.MISC, ModItems.PINK_SPOREBEAN_BAG_4).input(ModItems.PINK_SPOREBEAN, 4).input(Items.PAPER, 1).criterion(hasItem(ModItems.PINK_SPOREBEAN), conditionsFromItem(ModItems.PINK_SPOREBEAN)).offerTo(consumer, new Identifier(getRecipeName(ModItems.PINK_SPOREBEAN_BAG_4)));
        ShapelessRecipeJsonBuilder.create(RecipeCategory.MISC, ModItems.PINK_SPOREBEAN_BAG_3).input(ModItems.PINK_SPOREBEAN, 3).input(Items.PAPER, 1).criterion(hasItem(ModItems.PINK_SPOREBEAN), conditionsFromItem(ModItems.PINK_SPOREBEAN)).offerTo(consumer, new Identifier(getRecipeName(ModItems.PINK_SPOREBEAN_BAG_3)));
        ShapelessRecipeJsonBuilder.create(RecipeCategory.MISC, ModItems.PINK_SPOREBEAN_BAG_2).input(ModItems.PINK_SPOREBEAN, 2).input(Items.PAPER, 1).criterion(hasItem(ModItems.PINK_SPOREBEAN), conditionsFromItem(ModItems.PINK_SPOREBEAN)).offerTo(consumer, new Identifier(getRecipeName(ModItems.PINK_SPOREBEAN_BAG_2)));
        ShapelessRecipeJsonBuilder.create(RecipeCategory.MISC, ModItems.ORANGE_SPOREBEAN_BAG).input(ModItems.ORANGE_SPOREBEAN, 8).input(Items.PAPER, 1).criterion(hasItem(ModItems.ORANGE_SPOREBEAN), conditionsFromItem(ModItems.ORANGE_SPOREBEAN)).offerTo(consumer, new Identifier(getRecipeName(ModItems.ORANGE_SPOREBEAN_BAG)));
        ShapelessRecipeJsonBuilder.create(RecipeCategory.MISC, ModItems.ORANGE_SPOREBEAN_BAG_7).input(ModItems.ORANGE_SPOREBEAN, 7).input(Items.PAPER, 1).criterion(hasItem(ModItems.ORANGE_SPOREBEAN), conditionsFromItem(ModItems.ORANGE_SPOREBEAN)).offerTo(consumer, new Identifier(getRecipeName(ModItems.ORANGE_SPOREBEAN_BAG_7)));
        ShapelessRecipeJsonBuilder.create(RecipeCategory.MISC, ModItems.ORANGE_SPOREBEAN_BAG_6).input(ModItems.ORANGE_SPOREBEAN, 6).input(Items.PAPER, 1).criterion(hasItem(ModItems.ORANGE_SPOREBEAN), conditionsFromItem(ModItems.ORANGE_SPOREBEAN)).offerTo(consumer, new Identifier(getRecipeName(ModItems.ORANGE_SPOREBEAN_BAG_6)));
        ShapelessRecipeJsonBuilder.create(RecipeCategory.MISC, ModItems.ORANGE_SPOREBEAN_BAG_5).input(ModItems.ORANGE_SPOREBEAN, 5).input(Items.PAPER, 1).criterion(hasItem(ModItems.ORANGE_SPOREBEAN), conditionsFromItem(ModItems.ORANGE_SPOREBEAN)).offerTo(consumer, new Identifier(getRecipeName(ModItems.ORANGE_SPOREBEAN_BAG_5)));
        ShapelessRecipeJsonBuilder.create(RecipeCategory.MISC, ModItems.ORANGE_SPOREBEAN_BAG_4).input(ModItems.ORANGE_SPOREBEAN, 4).input(Items.PAPER, 1).criterion(hasItem(ModItems.ORANGE_SPOREBEAN), conditionsFromItem(ModItems.ORANGE_SPOREBEAN)).offerTo(consumer, new Identifier(getRecipeName(ModItems.ORANGE_SPOREBEAN_BAG_4)));
        ShapelessRecipeJsonBuilder.create(RecipeCategory.MISC, ModItems.ORANGE_SPOREBEAN_BAG_3).input(ModItems.ORANGE_SPOREBEAN, 3).input(Items.PAPER, 1).criterion(hasItem(ModItems.ORANGE_SPOREBEAN), conditionsFromItem(ModItems.ORANGE_SPOREBEAN)).offerTo(consumer, new Identifier(getRecipeName(ModItems.ORANGE_SPOREBEAN_BAG_3)));
        ShapelessRecipeJsonBuilder.create(RecipeCategory.MISC, ModItems.ORANGE_SPOREBEAN_BAG_2).input(ModItems.ORANGE_SPOREBEAN, 2).input(Items.PAPER, 1).criterion(hasItem(ModItems.ORANGE_SPOREBEAN), conditionsFromItem(ModItems.ORANGE_SPOREBEAN)).offerTo(consumer, new Identifier(getRecipeName(ModItems.ORANGE_SPOREBEAN_BAG_2)));
        ShapelessRecipeJsonBuilder.create(RecipeCategory.MISC, ModItems.WHITE_SPOREBEAN_BAG).input(ModItems.WHITE_SPOREBEAN, 8).input(Items.PAPER, 1).criterion(hasItem(ModItems.WHITE_SPOREBEAN), conditionsFromItem(ModItems.WHITE_SPOREBEAN)).offerTo(consumer, new Identifier(getRecipeName(ModItems.WHITE_SPOREBEAN_BAG)));
        ShapelessRecipeJsonBuilder.create(RecipeCategory.MISC, ModItems.WHITE_SPOREBEAN_BAG_7).input(ModItems.WHITE_SPOREBEAN, 7).input(Items.PAPER, 1).criterion(hasItem(ModItems.WHITE_SPOREBEAN), conditionsFromItem(ModItems.WHITE_SPOREBEAN)).offerTo(consumer, new Identifier(getRecipeName(ModItems.WHITE_SPOREBEAN_BAG_7)));
        ShapelessRecipeJsonBuilder.create(RecipeCategory.MISC, ModItems.WHITE_SPOREBEAN_BAG_6).input(ModItems.WHITE_SPOREBEAN, 6).input(Items.PAPER, 1).criterion(hasItem(ModItems.WHITE_SPOREBEAN), conditionsFromItem(ModItems.WHITE_SPOREBEAN)).offerTo(consumer, new Identifier(getRecipeName(ModItems.WHITE_SPOREBEAN_BAG_6)));
        ShapelessRecipeJsonBuilder.create(RecipeCategory.MISC, ModItems.WHITE_SPOREBEAN_BAG_5).input(ModItems.WHITE_SPOREBEAN, 5).input(Items.PAPER, 1).criterion(hasItem(ModItems.WHITE_SPOREBEAN), conditionsFromItem(ModItems.WHITE_SPOREBEAN)).offerTo(consumer, new Identifier(getRecipeName(ModItems.WHITE_SPOREBEAN_BAG_5)));
        ShapelessRecipeJsonBuilder.create(RecipeCategory.MISC, ModItems.WHITE_SPOREBEAN_BAG_4).input(ModItems.WHITE_SPOREBEAN, 4).input(Items.PAPER, 1).criterion(hasItem(ModItems.WHITE_SPOREBEAN), conditionsFromItem(ModItems.WHITE_SPOREBEAN)).offerTo(consumer, new Identifier(getRecipeName(ModItems.WHITE_SPOREBEAN_BAG_4)));
        ShapelessRecipeJsonBuilder.create(RecipeCategory.MISC, ModItems.WHITE_SPOREBEAN_BAG_3).input(ModItems.WHITE_SPOREBEAN, 3).input(Items.PAPER, 1).criterion(hasItem(ModItems.WHITE_SPOREBEAN), conditionsFromItem(ModItems.WHITE_SPOREBEAN)).offerTo(consumer, new Identifier(getRecipeName(ModItems.WHITE_SPOREBEAN_BAG_3)));
        ShapelessRecipeJsonBuilder.create(RecipeCategory.MISC, ModItems.WHITE_SPOREBEAN_BAG_2).input(ModItems.WHITE_SPOREBEAN, 2).input(Items.PAPER, 1).criterion(hasItem(ModItems.WHITE_SPOREBEAN), conditionsFromItem(ModItems.WHITE_SPOREBEAN)).offerTo(consumer, new Identifier(getRecipeName(ModItems.WHITE_SPOREBEAN_BAG_2)));
    }
}
